### ISSUE TITLE
Allow copying of generated award name

### ISSUE THREAD

**Issue by jamesmoss** [sillysecurityawards/awards-site#2]
I tried to highlight it to copy and paste to Slack but the toast has `pointer-events: none` on it. 

On a similar note, a share to slack or twitter button would be great.

**Comment by alexdunphy** [comment]
Hey @jamesmoss, sure thing - the award names should be easier to copy now. The text is selectable, and the names won't get dismissed while focused.

Social sharing links have been added to the header for Twitter & LinkedIn. Do you know off-hand if there's a way to share on Slack from the web? I saw https://api.slack.com/reference/deep-linking which looked promising, but I couldn't see a way to share a URL there.

**Comment by jamesmoss** [comment]
Awesome - it works great.

I don't think there's a share to slack button but copy and paste is fine for now. Thanks!
