### ISSUE TITLE
Nominate a silly security award: [TOP INFOSEC INNOVATOR AWARDS]

### ISSUE THREAD

**Issue by andrettv** [sillysecurityawards/awards-site#26]
Please add the following details to nominate an award for inclusion on the site:

### 
![image](
[(https://pbs.twimg.com/profile_images/1135558806279266306/eX89pO_q_400x400.png)]

If possible, please attach a logo for the awarding organisation - ideally a PNG/SVG around 600px on the longest side.

**Comment by 0xtf** [comment]
Thank you @andrettv. Added in https://github.com/sillysecurityawards/awards-site/commit/58be84068e8ea3cde277b73f889e624013703cda. Should be live soon.
