### ISSUE TITLE
Nominate a silly security award: [Global Finance Magazine Award]

### ISSUE THREAD

**Issue by andrettv** [sillysecurityawards/awards-site#27]
Please add the following details to nominate an award for inclusion on the site:

### [Logo image](
[(https://d2tyltutevw8th.cloudfront.net/media/image/safest-banks-2022-logo-1663607584.jpg)
/)]

**Comment by 0xtf** [comment]
Hi @andrettv. I couldn't find anything about awards pertaining to infosec. Seems they might have had a publication where they mentioned it? If you could add more information (ideally a program description of what they are doing, pricing details, etc) it would make it easier for us to add it to the website.

**Comment by andrettv** [comment]
> Hi @andrettv. I couldn't find anything about awards pertaining to infosec. Seems they might have had a publication where they mentioned it? If you could add more information (ideally a program description of what they are doing, pricing details, etc) it would make it easier for us to add it to the website.

See among sub-category winners „Best Information Security and Fraud Management“:

https://www.gfmag.com/magazine/september-2022/worlds-best-digital-banks-2022-round-1

https://www.citigroup.com/global/news/press-release/2022/citi-named-best-corporateinstitutional-digital-bank-in-16-latin-american-countries

https://www.goldmansachs.com/about-us/people-and-leadership/awards-and-rankings/business-and-innovation/

**Comment by andrettv** [comment]
No reply
