### ISSUE TITLE
Add Social Share to the header 

### ISSUE THREAD

**Issue by curphey** [sillysecurityawards/awards-site#3]
Be good if you can share the site on Twitter, LinkedIn and maybe even Slack

**Comment by alexdunphy** [comment]
Hey @curphey, share links have been added to the header for Twitter + LinkedIn now.

I'm not sure if there's a way to share a link on Slack from the web, but am having a quick look - please give me a shout if you've seen this done anywhere.

**Comment by curphey** [comment]
This LGTM. Lets forget slack for now.
