### ISSUE TITLE
Nominate a silly security award: World Future Awards

### ISSUE THREAD

**Issue by curphey** [sillysecurityawards/awards-site#38]
Please add the following details to nominate an award for inclusion on the site:

### Award name
World Future Awards

### Awarding organisation
https://worldfutureawards.com/

### Link to award page / organisation site
https://worldfutureawards.com/ a marketing company. This is a classic 

Founder & CEO at World Future Awards, at **Luxury Lifestyle Awards**, at Digital PR Agency Aura Communications,MA at Harvard Business School

### Reason for nomination
Pay to play - https://worldfutureawards.com/application-payment/

### Logo image
![WFA_logo_Black_HOR](https://github.com/sillysecurityawards/awards-site/assets/143776/43f36ff4-b941-4756-83dc-eb36228fec98)

If possible, please attach a logo for the awarding organisation - ideally a PNG/SVG around 600px on the longest side.

**Comment by curphey** [comment]
@0xtf I'll try and get to all of these awards today but of course feel free if you want / have time. Thanks for cleaning up the PR's yesterday.

**Comment by 0xtf** [comment]
> @0xtf I'll try and get to all of these awards today but of course feel free if you want / have time. Thanks for cleaning up the PR's yesterday.

I'll add them in a bit 👍🏼

**Comment by 0xtf** [comment]
Added in https://github.com/sillysecurityawards/awards-site/commit/630dc8d678489cecaaaff2d434391cd95ec76e19.
