### ISSUE TITLE
Social Share Image on Twitter

### ISSUE THREAD

**Issue by curphey** [sillysecurityawards/awards-site#6]
LinkedIn has a great social share image but this doesnt unfurl on Twitter. I suspect more sharing will be on Twitter so would be great to have the same. 
![Screenshot 2023-05-22 at 11 03 44](https://github.com/sillysecurityawards/awards-site/assets/143776/bcceccfa-1990-45ab-b008-89b9753acca3)

**Comment by alexdunphy** [comment]
Hey @curphey, meta tags for Twitter have been added, and this should be working now - though I only see the share image after posting a tweet, not in the composer right now (but maybe this will change when Twitter's share data cache updates):

<img width="634" alt="CleanShot 2023-05-22 at 11 26 17@2x" src="https://github.com/sillysecurityawards/awards-site/assets/1374671/70b74b66-62d7-4774-8c34-1960748857c4">

**Comment by alexdunphy** [comment]
Just closing this one off, as I'm getting the full image preview in the tweet composer now too:

<img width="631" alt="CleanShot 2023-05-22 at 11 44 54@2x" src="https://github.com/sillysecurityawards/awards-site/assets/1374671/b0bb6134-9760-4370-baa3-a1078383418c">
